scrape_configs:
  - job_name: 'order-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus' ##prometheus endpoint
    static_configs:
      - targets: ['localhost:61570'] ## host and port for your mis